#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Sep 04, 2018 02:01:00 AM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import ANALYSE_RES_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = ANALYSE_RESULTS (root)
    ANALYSE_RES_support.init(root, top)
    root.mainloop()

w = None
def create_ANALYSE_RESULTS(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = ANALYSE_RESULTS (w)
    ANALYSE_RES_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_ANALYSE_RESULTS():
    global w
    w.destroy()
    w = None


class ANALYSE_RESULTS:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("600x450+423+123")
        top.title("ANALYSE RESULTS")
        top.configure(borderwidth="20")
        top.configure(relief="groove")
        top.configure(background="#d9d9d9")
        top.configure(takefocus="023")
        top.configure(width="8")



        self.Label1 = Label(top)
        self.Label1.place(relx=0.15, rely=0.2, height=21, width=104)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''SHOW MARKS''')
        self.Label1.configure(width=104)

        self.menubar = Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)



        self.Label2 = Label(top)
        self.Label2.place(relx=0.13, rely=0.33, height=21, width=126)
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''HISTOGRAM''')

        self.Button1 = Button(top)
        self.Button1.place(relx=0.6, rely=0.18, height=34, width=86)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''SHOW''')
        self.Button1.configure(width=86)

        self.Label3 = Label(top)
        self.Label3.place(relx=0.17, rely=0.47, height=21, width=74)
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''PIE CHART''')

        self.Button3 = Button(top)
        self.Button3.place(relx=0.4, rely=0.71, height=44, width=101)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''BACK''')
        self.Button3.configure(width=101)

        self.Button4 = Button(top)
        self.Button4.place(relx=0.6, rely=0.44, height=34, width=86)
        self.Button4.configure(activebackground="#d9d9d9")
        self.Button4.configure(activeforeground="#000000")
        self.Button4.configure(background="#d9d9d9")
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(foreground="#000000")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(pady="0")
        self.Button4.configure(text='''SHOW''')
        self.Button4.configure(width=86)

        self.Button2 = Button(top)
        self.Button2.place(relx=0.6, rely=0.31, height=34, width=87)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''SHOW''')
        self.Button2.configure(width=87)






if __name__ == '__main__':
    vp_start_gui()



